name: Deploy Jekyll

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:

      - name: checkout master
        uses: actions/checkout@v2

      - name: checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: 'gh-pages'

      - name: setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: jekyll build
        run: JEKYLL_ENV=production bundle exec jekyll build --destination gh-pages

      - name: push gh-pages
        run: |
          git config user.name "${GITHUB_ACTOR}" && \
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
          cd gh-pages && \
          git add . && \
          git commit -m "jekyll build from Action ${GITHUB_SHA}" && \
          git push
