name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      # Use GitHub Actions' cache to shorten build times and decrease load on servers.
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - run: bundle config path vendor/bundle

      - run: bundle install --jobs 4 --retry 3

      - run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
